name: "Renew SSL certificate"

on:
  workflow_dispatch:
  schedule:
    # Runs at 12:00 PM on the 1st day of every month.
    - cron: '0 12 1 * *'

jobs:
  # This job renews the SSL certificate and sends an email notification upon failure.
  renew-and-notify:
    name: Renew SSL certificate
    runs-on: ubuntu-22.04
    steps:
      # Check out the repository to access the renewal scripts.
      - name: Check out repository
        uses: actions/checkout@v4

      # Execute the main script to renew the SSL certificate.
      - name: Renew SSL certificate
        run: ./run.sh
        working-directory: ./scripts

      # If any of the previous steps fail, send an email notification.
      - name: Send failure e-mail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          subject: "URGENT: Showroom SSL certificate renewal failed"
          body: "The automated renewal of the SSL certificate for the showroom has failed. Please investigate immediately."
          to: yasinghasemi.2003@gmail.com
          from: GitHub Actions (Showroom SSL) <actions@github.com>
          priority: high
          secure: false
          server_address: smtp.office365.com
          server_port: 587

