name: main - production synchronization

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - production

jobs:
  # Job A: whenever main gets a new push (merge or commit), creating a PR to production
  create-production-pr:
    if: ${{ github.ref == 'refs/heads/main' &&  !startsWith(github.event.head_commit.message, 'Revert') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Get the squashed commit subject
        id: get_subject
        run: |
          SUBJECT=$(git log -1 --pretty=format:%s $GITHUB_SHA)
          echo "SUBJECT=$SUBJECT" >> $GITHUB_ENV

      - name: Extract PR number from subject
        id: get_pr_ref
        run: |
          set -euo pipefail
          PR_NUM=$(echo "$SUBJECT" | sed -nE 's/.*\(#([0-9]+)\).*/\1/p')
          echo "PR_NUM=$PR_NUM" >> $GITHUB_ENV

      - name: Derive clean title
        id: get_title
        run: |
          PR_TITLE=$(echo "$SUBJECT" | sed -E 's/ *\(#\d+\)$//')
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Derive ticket key for branch name
        id: get_ticket
        shell: bash
        run: |
          set -euo pipefail

          FULL_MSG=$(git log -1 --pretty=format:'%B' $GITHUB_SHA)

          mapfile -t PARENS < <(grep -oE '\([^#][^)]*\)' <<<"$FULL_MSG")

          TICKET_NUM=""
          for blk in "${PARENS[@]}"; do
            if n=$(grep -oE '[0-9]+' <<<"$blk"); then
              TICKET_NUM="$n"
              break
            fi
          done

          if [[ -n "$TICKET_NUM" ]]; then
            TICKET="EC-${TICKET_NUM}"
          else
            TICKET="$GITHUB_SHA"
          fi

          echo "Derived ticket: $TICKET"
          echo "TICKET=$TICKET" >> $GITHUB_ENV

      - name: Fetch & switch to production
        run: |
          git fetch origin production
          git checkout production

      - name: Create & switch to prod-branch
        run: |
          BRANCH="prod-${TICKET}"
          git checkout -b "$BRANCH"

      - name: Configure Git committer
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick the squashed commit
        run: |
          git remote add main_repo "${{ github.server_url }}/${{ github.repository }}.git"
          git fetch main_repo main
          git cherry-pick $GITHUB_SHA --allow-empty

      - name: Push prod-branch back to origin
        run: |
          git push --set-upstream origin "prod-${TICKET}"

      - name: Compute PR body text
        id: compute_body
        run: |
          set -euo pipefail

          COMMIT_LINK="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          echo "COMMIT_LINK=$COMMIT_LINK" >> $GITHUB_ENV

          if [ -n "$PR_NUM" ]; then
            PR_LINK="https://github.com/${GITHUB_REPOSITORY}/pull/${PR_NUM}"
            echo "PR_LINK=$PR_LINK" >> $GITHUB_ENV

            echo "PR_BODY=Cherry-pick of commit \`${GITHUB_SHA}\` (${COMMIT_LINK}) from ${PR_LINK}" >> $GITHUB_ENV
          else
            echo "PR_LINK=" >> $GITHUB_ENV

            echo "PR_BODY=Cherry-pick of commit \`${GITHUB_SHA}\` (${COMMIT_LINK}). This PR is not associated with any JIRA item." >> $GITHUB_ENV
          fi

      - name: Create PR into production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr create \
            --base production \
            --head prod-${TICKET} \
            --title "[prod] $PR_TITLE" \
            --body "$PR_BODY"


  # Job B: whenever production sees a revert commit, reproduce that revert on main.
  revert-on-production:
    if: ${{ github.ref == 'refs/heads/production' && startsWith(github.event.head_commit.message, 'Revert') &&  github.event.head_commit.author.username != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0

      - name: Extract original & revert PR numbers
        id: extract_revert_pr
        shell: bash
        env:
          MSG: ${{ github.event.head_commit.message }}
        run: |
          set -euo pipefail

          NUMS=( $(grep -oE '#[0-9]+' <<<"$MSG" | tr -d '#') )

          LAST_TWO=( "${NUMS[@]: -2}" )
          ORIGINAL_PR_NUM=${LAST_TWO[0]}
          REVERT_PR_NUM=${LAST_TWO[1]}

          if [ -z "$ORIGINAL_PR_NUM" ]; then
            echo "Couldn't find the original PR number in message" >&2
            exit 1
          fi

          echo "ORIGINAL_PR_NUM=$ORIGINAL_PR_NUM" >> $GITHUB_ENV
          echo "REVERT_PR_NUM=$REVERT_PR_NUM" >> $GITHUB_ENV

      - name: Fetch and debug the production PR body
        id: fetch_pr_body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          BODY=$(gh pr view "$ORIGINAL_PR_NUM" \
            --repo "$GITHUB_REPOSITORY" \
            --json body \
            --jq '.body // ""')
          echo "BODY_RAW<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Extract original main commit SHA
        shell: bash
        run: |
          set -euo pipefail

          mapfile -t IDS < <(grep -oE '[0-9a-f]{7,40}' <<<"$BODY_RAW")

          if [ "${#IDS[@]}" -eq 0 ]; then
            echo "No SHA found in PR body; aborting" >&2
            exit 1
          fi

          MAIN_SHA="${IDS[0]}"
          echo "MAIN_SHA=$MAIN_SHA" >> $GITHUB_ENV

      - name: Check out main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Create revert branch
        id: get_revert_branch
        run: |
          set -euo pipefail
          BRANCH="revert-from-prod-${MAIN_SHA}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout -b "$BRANCH"

      - name: Configure committer
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Revert the main commit
        run: |
          set -euo pipefail
          git revert "$MAIN_SHA" --no-edit

      - name: Push revert branch
        run: |
          git push --set-upstream origin "revert-from-prod-${MAIN_SHA}"

      - name: Create revert PR on main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          EXISTING=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --state open \
            --head "revert-from-prod-${MAIN_SHA}" \
            --base main \
            --json number \
            --jq '.[0].number // ""')

          if [ -n "$EXISTING" ]; then
            echo "Revert PR already open."
            exit 0
          fi

          REVERT_PR_LINK="https://github.com/${GITHUB_REPOSITORY}/pull/${REVERT_PR_NUM}"

          gh auth setup-git
          gh pr create \
            --base main \
            --head "revert-from-prod-${MAIN_SHA}" \
            --title "[main] production revert of ${MAIN_SHA}" \
            --body "This reverts commit \`${MAIN_SHA}\`, due to a revert on production PR [#${REVERT_PR_NUM}](${REVERT_PR_LINK})." \

  # Job C: whenever main sees a revert (from PR or commit) and there’s an open PR for production, cherry-pick that same revert into that PR branch, or create a new
  # PR when non exists. The key here is the word Revert in the commit message.
  revert-on-main:
    if: ${{ github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'Revert') && github.event.head_commit.author.username != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    env:
      FULL_MSG: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Determine branch suffix (ticket or SHA)
        id: parse_branch_suffix
        shell: bash
        run: |
          set -euo pipefail

          # grab the full commit message (subject + body + trailers)
          FULL_MSG=$(git log -1 --pretty=format:'%B' $GITHUB_SHA)

          # collect every parenthetical that does not start with “#”
          mapfile -t PARENS < <(grep -oE '\([^#][^)]*\)' <<<"$FULL_MSG")

          # pull digits out of the first matching block
          SUFFIX_NUM=""
          for blk in "${PARENS[@]}"; do
            if n=$(grep -oE '[0-9]+' <<<"$blk"); then
              SUFFIX_NUM="$n"
              break
            fi
          done

          # if we got digits, prefix with “EC-“, otherwise fall back to SHA
          if [[ -n "$SUFFIX_NUM" ]]; then
            SUFFIX="EC-${SUFFIX_NUM}"
          else
            SUFFIX="$GITHUB_SHA"
          fi

          echo "Determined suffix: $SUFFIX"
          echo "BRANCH_SUFFIX=$SUFFIX" >> $GITHUB_ENV

      - name: Find or create prod-$BRANCH_SUFFIX branch
        id: setup_prod_branch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          # 1) Check if there's already an OPEN PR with head=prod-$BRANCH_SUFFIX
          EXISTING_HEAD=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --state open \
            --base production \
            --head "prod-${BRANCH_SUFFIX}" \
            --json headRefName \
            --jq '.[0].headRefName // ""')

          if [[ -n "$EXISTING_HEAD" ]]; then
            echo "🔁 Re-using existing branch $EXISTING_HEAD (PR already open)"
            BRANCH="$EXISTING_HEAD"
            git fetch origin "$BRANCH":"$BRANCH"
            git checkout "$BRANCH"
          else
            echo "✨ No PR yet; creating new branch prod-${BRANCH_SUFFIX} from production"
            git fetch origin production
            BRANCH="prod-${BRANCH_SUFFIX}"
            git checkout -b "$BRANCH" origin/production
          fi

          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Configure Git committer
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick the revert
        run: |
          set -euo pipefail
          git cherry-pick "${BRANCH_SUFFIX}" --allow-empty

      - name: push
        run: |
          git push origin HEAD:prod-${BRANCH_SUFFIX}

      - name: PR creation (if doesn't exist)
        id: check_or_create_pr
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          EXISTING=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --state open \
            --base production \
            --head prod-${BRANCH_SUFFIX} \
            --json number \
            --jq '.[0].number // ""')

          if [[ -n "$EXISTING" ]]; then
            exit 0
          fi

          gh auth setup-git
          gh pr create \
            --repo "$GITHUB_REPOSITORY" \
            --base production \
            --head prod-${BRANCH_SUFFIX} \
            --title "[prod] Cherry-pick revert of ${BRANCH_SUFFIX}" \
            --body "Cherry-pick of revert commit \`${BRANCH_SUFFIX}\` (https://github.com/${GITHUB_REPOSITORY}/commit/${BRANCH_SUFFIX}) from main."
