name: main - production synchronization

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - production

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  # Job A: whenever main gets a new push (merge or commit), this creates a PR to production.
  create-production-pr:
    if: ${{ github.ref == 'refs/heads/main' &&  !contains(github.event.head_commit.message, 'Revert') }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_SHA:  ${{ github.event.commits[0].id }}
    steps:
      - name: Check out main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Debug show full push payload
        run: |
          echo "=== FULL PUSH EVENT ==="
          cat "$GITHUB_EVENT_PATH"
          
      - name: Get the squashed commit subject
        run: |
          SUBJECT=$(git log -1 --pretty=format:%s $TARGET_SHA)
          echo "SUBJECT=$SUBJECT" >> $GITHUB_ENV

      - name: Extract PR number from subject
        run: |
          PR_NUM=$(echo "$SUBJECT" | sed -nE 's/.*\(#([0-9]+)\).*/\1/p')
          echo "PR_NUM=$PR_NUM" >> $GITHUB_ENV

      - name: Derive clean title
        run: |
          PR_TITLE=$(echo "$SUBJECT" | sed -E 's/ *\(#\d+\)$//')
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Fetch & switch to production
        run: |
          git fetch origin production
          git checkout production

      - name: Create & switch to prod-branch
        run: |
          BRANCH="prod-${TARGET_SHA}"
          git checkout -b "$BRANCH"

      - name: Configure Git committer
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick the squashed commit
        run: |
          git remote add main_repo "${{ github.server_url }}/${{ github.repository }}.git"
          git fetch main_repo main
          git cherry-pick $TARGET_SHA --allow-empty

      - name: Push prod-branch back to origin
        run: |
          git push --set-upstream origin "prod-${TARGET_SHA}"

      - name: Compute PR body text
        run: |
          COMMIT_LINK="https://github.com/${GITHUB_REPOSITORY}/commit/${TARGET_SHA}"
          echo "COMMIT_LINK=$COMMIT_LINK" >> $GITHUB_ENV

          if [ -n "$PR_NUM" ]; then
            PR_LINK="https://github.com/${GITHUB_REPOSITORY}/pull/${PR_NUM}"
            echo "PR_LINK=$PR_LINK" >> $GITHUB_ENV

            echo "PR_BODY=Cherry-pick of commit \`${TARGET_SHA}\` (${COMMIT_LINK}) from ${PR_LINK}" >> $GITHUB_ENV
          else
            echo "PR_BODY=Cherry-pick of commit \`${TARGET_SHA}\` (${COMMIT_LINK}). This PR is not associated with any JIRA item." >> $GITHUB_ENV
          fi

      - name: Create PR into production
        run: |
          gh auth setup-git
          gh pr create \
            --base production \
            --head prod-${TARGET_SHA} \
            --title "[prod] $PR_TITLE" \
            --body "$PR_BODY" \
            --label "auto-release"

  # Job B: whenever production sees a revert commit, reproduce that revert on main and merges.
  revert-on-production:
    if: ${{ github.ref == 'refs/heads/production' && contains(github.event.head_commit.message, 'Revert') &&  github.event.head_commit.author.username != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MSG: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0

      - name: Extract original & revert PR numbers
        run: |
          mapfile -t NUMS < <(grep -oE '#[0-9]+' <<<"$MSG" | tr -d '#')
      
          if (( ${#NUMS[@]} < 2 )); then
            echo "Error: commit message must include both original and revert PR numbers" >&2
            exit 1
          fi
      
          ORIGINAL_PR_NUM=${NUMS[-2]}
          REVERT_PR_NUM=${NUMS[-1]}

          echo "ORIGINAL_PR_NUM=$ORIGINAL_PR_NUM" >> $GITHUB_ENV
          echo "REVERT_PR_NUM=$REVERT_PR_NUM" >> $GITHUB_ENV

      - name: Fetch and debug the production PR body
        run: |
          BODY=$(gh pr view "$ORIGINAL_PR_NUM" \
            --repo "$GITHUB_REPOSITORY" \
            --json body \
            --jq '.body // ""')
          echo "BODY_RAW<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Extract original main commit SHA
        run: |
          mapfile -t IDS < <(grep -oE '[0-9a-f]{7,40}' <<<"$BODY_RAW")

          if [ "${#IDS[@]}" -eq 0 ]; then
            echo "No SHA found in PR body; aborting." >&2
            exit 1
          fi

          MAIN_SHA="${IDS[0]}"
          echo "MAIN_SHA=$MAIN_SHA" >> $GITHUB_ENV

      - name: Check out main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Create revert branch
        run: |
          BRANCH="main-revert-${MAIN_SHA}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout -b "$BRANCH"

      - name: Configure committer
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Revert the main commit
        run: |
          git revert "$MAIN_SHA" --no-edit

      - name: Push revert branch
        run: |
          git push --set-upstream origin "main-revert-${MAIN_SHA}"

      - name: Create PR on main
        run: |
          gh auth setup-git

          gh pr create \
            --repo "${{ github.repository }}" \
            --base main \
            --head "main-revert-${MAIN_SHA}" \
            --title "[main] production revert of ${MAIN_SHA}" \
            --body "This reverts commit \`${MAIN_SHA}\` from production." \
            --label "auto-release"
            
  # Job C: whenever main sees a revert (from PR or commit) and there’s an open PR for production, cherry-pick that same revert into that PR branch, or create a new
  # PR when non exists. The key here is the word "Revert" in the commit message.
  revert-on-main:
    if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'Revert') && github.event.head_commit.author.username != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MSG: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Determine branch suffix (last SHA in commit message)
        run: |
          MSG=$(git log -1 --pretty=format:'%B' $GITHUB_SHA)
          SUFFIX=$(grep -oE '[0-9a-f]{7,40}' <<<"$MSG" | tail -n1)
          echo "BRANCH_SUFFIX=$SUFFIX" >> $GITHUB_ENV

      - name: Prepare prod branch for this SHA
        run: |
          BRANCH="prod-${BRANCH_SUFFIX}"

          EXISTING=$(gh pr list \
            --repo "${{ github.repository }}" \
            --state open \
            --base production \
            --head "$BRANCH" \
            | head -1 | awk '{print $1}')

          if [[ -n "$EXISTING" ]]; then
            git fetch origin "$BRANCH:$BRANCH"
            git checkout "$BRANCH"
          else
            git fetch origin production
            git branch -D "$BRANCH" 2>/dev/null || true
            git checkout -b "$BRANCH" origin/production
          fi

      - name: Configure Git committer
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cherry-pick the revert
        run: |
          git cherry-pick "${GITHUB_SHA}" --allow-empty

      - name: push
        run: |
          git push origin HEAD:prod-${BRANCH_SUFFIX}

      - name: PR creation (if doesn't exist)
        run: |
          EXISTING=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --state open \
            --base production \
            --head prod-${BRANCH_SUFFIX} \
            | head -1 | awk '{print $1}')

          if [[ -n "$EXISTING" ]]; then
            echo "PR #$EXISTING already open; skipping"
            exit 0
          fi

          gh pr create \
            --repo "$GITHUB_REPOSITORY" \
            --base production \
            --head prod-${BRANCH_SUFFIX} \
            --title "[prod] Cherry-pick revert of ${BRANCH_SUFFIX}" \
            --body "Cherry-pick of revert commit \`${BRANCH_SUFFIX}\` (https://github.com/${GITHUB_REPOSITORY}/commit/${BRANCH_SUFFIX}) from main." \
            --label "auto-release"

